### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by konstantinos-kb** [bundesAPI/handelsregister#15]
Sorry for the question in advance - I am very new to coding and GitHub.

Is your API already available and working and if so, how can I use it?

Thanks in advance!

**Comment by severinsimmler** [comment]
Hi @konstantinos-kb,

you can use the CLI to fetch company data: https://github.com/bundesAPI/handelsregister#command-line-interface

But be careful with the rate limits:

> Mehr als 60 Abrufe pro Stunde widersprechen der Nutzungsordnung.

If you scrape too much with the same IP, they will permanently block you.

**Comment by konstantinos-kb** [comment]
Thanks for the answer! How would such an example execution look like (confused about how args have to look like exactly).

**Comment by konstantinos-kb** [comment]
For example - for passing the SCHLAGWOERTER - how would these arguments look like?

**Comment by severinsimmler** [comment]
Probably something like:

```
python handelsregister.py -s "deutsche bahn" -so all
```

**Comment by konstantinos-kb** [comment]
This didn't seem to work - am I missing anything?

**Comment by ChrisCh4padia** [comment]
You are indeed not alone. 

Pasting the above example : 
`python handelsregister.py -s "deutsche bahn" -so all`

gives me:
```
Traceback (most recent call last):
File "/home/chris/Dokumente/handelsregister-main/handelsregister.py", line 180, in <module>
if companies := h.search_company():
File "/home/chris/Dokumente/handelsregister-main/handelsregister.py", line 71, in search_company
self.browser["form:schlagwortOptionen"] = schlagwortOptionen.get(args.schlagwortOptionen)
NameError: name 'schlagwortOptionen' is not defined
```
also not experienced in python, so this could be my fault.

Running latest Garuda Linux with Python 3.10

**Comment by wirthual** [comment]
I added some minor changes to make it executable:
` python handelsregister.py -s "deutsche bahn" -so all`

Gives me this now:
```
name: "Die Bärchen" unabhängige Eltern-Kind-Initiative e.V.
court: Bavaria   District court München VR 15251
state: München
status: currently registered
history:
1.) "Die Bärchen" - unabhängige Eltern-Kind-Initiative von DB-und Sparda Bank-Eltern e.V. 1.) München
2.) "Die Bärchen" - unabhängige Eltern-Kind-Initiative e.V. von Deutsche Bahn-und Sparda Bank-Eltern. 2.) München
3.) "Die Bärchen" - unabhängige Eltern-Kind-Initiative von DB-und Sparda Bank-Eltern e.V. 3.) München
name: Aurelis Beteiligungs-GmbH
court: Hesse   District court Frankfurt am Main HRB 54087
state: Eschborn
status: currently registered
history:
1.) Aurelis Management GmbH 1.) Eschborn
2.) Aurelis Management GmbH 2.) Berlin
name: DB Projekt Stuttgart-Ulm GmbH
court: Baden-Württemberg   District court Stuttgart HRB 745715
state: Stuttgart
status: currently registered
history:
name: DEVK Deutsche Eisenbahn Versicherung Lebensversicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bahn
court: North Rhine-Westphalia   District court Köln HRB 7864
state: Köln
status: currently registered
history:
1.) DEVK Deutsche Eisenbahn Versicherung Lebensversicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bahn AG 1.) Köln
name: DEVK Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bahn
court: North Rhine-Westphalia   District court Köln HRB 8234
state: Köln
status: currently registered
history:
1.) DEVK Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherugnsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bundesbahn 1.) Köln
2.) Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bundesbahn 2.) Köln
3.) DEVK Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bahn AG 3.) Köln
name: Deutsche Bahn Aktiengesellschaft
court: Berlin   District court Berlin (Charlottenburg) HRB 50000
state: Berlin
status: currently registered
history:
name: Deutsche Bahn Connect GmbH
court: Hesse   District court Frankfurt am Main HRB 41769
state: Frankfurt am Main
status: currently registered
history:
1.) DBFuhrparkService GmbH 1.) Frankfurt am Main
2.) DB FuhrparkService GmbH 2.) Frankfurt am Main
name: Deutsche Bahn Digital Ventures GmbH
court: Berlin   District court Berlin (Charlottenburg) HRB 181864
state: Berlin
status: currently registered
history:
name: Deutsche Bahn Finance GmbH
court: Berlin   District court Berlin (Charlottenburg) HRB 189333
state: Berlin
status: currently registered
history:
name: Deutsche Bahn Golf-Club
court: Hesse   District court Frankfurt am Main VR 11977
state: Frankfurt am Main
status: currently registered
history:
1.) Deutscher Eisenbahner Golf - Club 1.) Frankfurt am Main

```

**Comment by ChrisCh4padia** [comment]
Can confirm. Works great Now.
