### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Shiroikage** [bundesAPI/handelsregister#21]
bei der Suche nach "Aachener Bank eG" kommt ein index out of range error.
Getestet im CLI-Tool (`python handelsregister.py -s "Aachener Bank eG" -so all`) als auch über API-Abfrage in-code (`HandelsRegister(debug=False, force=False, schlagwoerter='Aachener Bank eG', schlagwortOptionen='all')`).

```
Traceback (most recent call last):
  File "/home/NAME/Code/PROJEKTNAME/handelsregister/handelsregister.py", line 185, in <module>
    companies = h.search_company()
  File "/home/NAME/Code/PROJEKTNAME/handelsregister/handelsregister.py", line 95, in search_company
    return get_companies_in_searchresults(html)
  File "/home/NAME/Code/PROJEKTNAME/handelsregister/handelsregister.py", line 136, in get_companies_in_searchresults
    d = parse_result(result)
  File "/home/NAME/Code/PROJEKTNAME/handelsregister/handelsregister.py", line 114, in parse_result
    d['history'].append((cells[i], cells[i+1])) # (name, location)
IndexError: list index out of range
```

**Comment by Shiroikage** [comment]
duplicate -> https://github.com/bundesAPI/handelsregister/issues/20#issue-1527183025
